version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - app-build:/app/build

  nginx:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - app-build:/usr/share/nginx/html

  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"

volumes:
  app-build: